### ISSUE TITLE
I encountered the following problems when I used `restapi.py`

### ISSUE THREAD

**Issue by Yue-plus** [robmarkcole/yolov5-flask#33]
I encountered the following problems when I used `restapi.py`:
当我使用 `restapi.py` 时，我遇到了以下问题：

```text
PS D:\code\yolov5-flask> python --version
Python 3.10.8
PS D:\code\yolov5-flask> python .\restapi.py
Using cache found in C:\Users\Yue_plus/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2022-11-10 Python-3.10.8 torch-1.13.0+cpu CPU

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
 * Serving Flask app 'restapi'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.3.3:5000
Press CTRL+C to quit
Exception on /v1/object-detection/yolov5s [POST]
Traceback (most recent call last):
  File "C:\Users\Yue_plus\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Yue_plus\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Yue_plus\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Yue_plus\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'predict' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [10/Nov/2022 17:04:18] "POST /v1/object-detection/yolov5s HTTP/1.1" 500 -
```

**Comment by Yue-plus** [comment]
There is also `webapp.py` No matter what the picture uploads, it will return this cat.
还有 `webapp.py` 无论上传什么图片都会返回这只猫。


![image](https://user-images.githubusercontent.com/33195150/201048516-ae9f3408-c6e7-4742-8408-1897e26f310f.png)

But in the project directory, there is a result:
但在项目目录下是有生成结果的：

![image](https://user-images.githubusercontent.com/33195150/201049204-daec0e32-dba9-470b-a902-09e5a9a6ed74.png)

**Comment by Yue-plus** [comment]
```text
PS D:\code\yolov5-flask> python --version
Python 3.10.8
PS D:\code\yolov5-flask> pip install -r .\requirements.txt
Requirement already satisfied: flask in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: requests in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: matplotlib>=3.2.2 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 5)) (3.6.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 6)) (1.23.4)
Requirement already satisfied: opencv-python>=4.1.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 7)) (4.6.0.66)
Requirement already satisfied: Pillow>=7.1.2 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 8)) (9.3.0)
Requirement already satisfied: PyYAML>=5.3.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 9)) (6.0)
Requirement already satisfied: scipy>=1.4.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 11)) (1.9.3)
Requirement already satisfied: torch>=1.7.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 12)) (1.13.0)
Requirement already satisfied: torchvision>=0.8.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 13)) (0.14.0)
Requirement already satisfied: tqdm>=4.64.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 14)) (4.64.1)
Requirement already satisfied: seaborn>=0.11.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 15)) (0.12.1)
Requirement already satisfied: pandas in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 16)) (1.5.1)
Requirement already satisfied: ipython in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 19)) (8.6.0)
Requirement already satisfied: psutil in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 20)) (5.9.4)
Requirement already satisfied: thop>=0.1.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from -r .\requirements.txt (line 21)) (0.1.1.post2209072238)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from flask->-r .\requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from flask->-r .\requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: click>=8.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from flask->-r .\requirements.txt (line 1)) (8.1.3)
Requirement already satisfied: Werkzeug>=2.2.2 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from flask->-r .\requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from requests->-r .\requirements.txt (line 2)) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from requests->-r .\requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from requests->-r .\requirements.txt (line 2)) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from requests->-r .\requirements.txt (line 2)) (3.4)
Requirement already satisfied: packaging>=20.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.2->-r .\requirements.txt (line 5)) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.2->-r .\requirements.txt (line 5)) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.2->-r .\requirements.txt (line 5)) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.2->-r .\requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.2->-r .\requirements.txt (line 5)) (1.0.6)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.2->-r .\requirements.txt (line 5)) (4.38.0)
Requirement already satisfied: cycler>=0.10 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.2->-r .\requirements.txt (line 5)) (0.11.0)
Requirement already satisfied: typing-extensions in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.7.0->-r .\requirements.txt (line 12)) (4.4.0)
Requirement already satisfied: colorama in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.64.0->-r .\requirements.txt (line 14)) (0.4.6)
Requirement already satisfied: pytz>=2020.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from pandas->-r .\requirements.txt (line 16)) (2022.6)
Requirement already satisfied: stack-data in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (0.6.0)
Requirement already satisfied: backcall in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (0.2.0)
Requirement already satisfied: matplotlib-inline in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>3.0.1 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (3.0.32)
Requirement already satisfied: pygments>=2.4.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (2.13.0)
Requirement already satisfied: pickleshare in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (0.7.5)
Requirement already satisfied: decorator in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (0.18.1)
Requirement already satisfied: traitlets>=5 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from ipython->-r .\requirements.txt (line 19)) (5.5.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython->-r .\requirements.txt (line 19)) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from Jinja2>=3.0->flask->-r .\requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: wcwidth in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from prompt-toolkit<3.1.0,>3.0.1->ipython->-r .\requirements.txt (line 19)) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.2.2->-r .\requirements.txt (line 5)) (1.16.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython->-r .\requirements.txt (line 19)) (2.1.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython->-r .\requirements.txt (line 19)) (1.2.0)
Requirement already satisfied: pure-eval in c:\users\yue_plus\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython->-r .\requirements.txt (line 19)) (0.2.2)
PS D:\code\yolov5-flask>
```

**Comment by icelts** [comment]
you solved it?

**Comment by robmarkcole** [comment]
Hmm my error:
```
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
```
